[workspace]
members=[
    # macros (pre-processing)
    "macros/ast",
    "macros/macros",
    "macros/optimiser",
    # runtime crates
    "runtime/myoxine",
    "runtime/cache",
    "runtime/executor",
    "runtime/query",
    # command line interface
    "cli"
]