name: CI
on: [push, pull_request]
jobs:
  check:
    name: Check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        rustc: ["stable", "beta", "nightly"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{matrix.rustc}}
          override: true
          components: rustfmt, clippy
      - name: test
        run: cargo test
      - name: rustfmt
        run: cargo fmt --all -- --check
      - name: clippy
        run: cargo clippy -- -D warnings
